version: "3.8"

services:
  identity_server:
    restart: on-failure
    ports:
      - "1001:1001"
    environment:
      ASPNETCORE_URLS: "https://+:1001"
      ASPNETCORE_Kestrel__Certificates__Default__Password: 12345
      ASPNETCORE_Kestrel__Certificates__Default__Path: /https/aspnetapp.pfx
      ConnectionStrings__Postgres: "Host=database;Username=postgres;Password=postgres;Database=itf"
      OAuth__Google__ClientId: $GOOGLE_CLIENT_ID
      OAuth__Google__ClientSecret: $GOOGLE_CLIENT_SECRET
    volumes:
      - ~/.aspnet/https:/https:ro
  itf:
    restart: on-failure
    ports:
      - "2001:2001"
    environment:
      ASPNETCORE_URLS: "https://+:2001"
      ASPNETCORE_Kestrel__Certificates__Default__Password: 12345
      ASPNETCORE_Kestrel__Certificates__Default__Path: /https/aspnetapp.pfx
    volumes:
      - ~/.aspnet/https:/https:ro
  chat:
    restart: on-failure
    ports:
      - "3001:3001"
    environment:
      ASPNETCORE_URLS: "https://+:3001"
      ASPNETCORE_Kestrel__Certificates__Default__Password: 12345
      ASPNETCORE_Kestrel__Certificates__Default__Path: /https/aspnetapp.pfx
    volumes:
      - ~/.aspnet/https:/https:ro
  database:
    restart: on-failure
    ports:
      - "5432:5432"
    volumes:
      - database_vol:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "itf"

volumes:
  database_vol: