FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /build

COPY ["server/Services/ITF/ITF.Api/ITF.Api.csproj", "server/Services/ITF/ITF.Api/ITF.Api.csproj"]
COPY ["server/Services/ITF/ITF.Application/ITF.Application.csproj", "server/Services/ITF/ITF.Application/ITF.Application.csproj"]
COPY ["server/Services/ITF/ITF.Domain/ITF.Domain.csproj", "server/Services/ITF/ITF.Domain/ITF.Domain.csproj"]
COPY ["server/Services/ITF/ITF.Infrastructure/ITF.Infrastructure.csproj", "server/Services/ITF/ITF.Infrastructure/ITF.Infrastructure.csproj"]

RUN dotnet restore "server/Services/ITF/ITF.Api/ITF.Api.csproj"

COPY . .
WORKDIR "/build/server/Services/ITF/ITF.Api"

RUN dotnet build "ITF.Api.csproj" -c Release --no-restore
RUN dotnet publish "ITF.Api.csproj" -c Release -o /published-app --no-restore

FROM mcr.microsoft.com/dotnet/aspnet:6.0
WORKDIR /itf

COPY --from=build /published-app ./

ENTRYPOINT ["dotnet", "ITF.Api.dll"]