version: "3.8"

services:
  identity_server:
    restart: on-failure
    ports:
      - "1000:1000"
    environment:
      ASPNETCORE_URLS: "http://+:1000"
      ConnectionStrings__Postgres: "Host=database;Username=postgres;Password=postgres;Database=itf"
      OAuth__Google__ClientId: $GOOGLE_CLIENT_ID
      OAuth__Google__ClientSecret: $GOOGLE_CLIENT_SECRET
  database:
    restart: on-failure
    ports:
      - "5432:5432"
    volumes:
      - database_vol:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "itf"

volumes:
  database_vol: