name: ITF Frontend CI/CD

on:
  push:
    paths:
      - 'client/**'
      - '.github/workflows/itf-frontend.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'client/**'
      - '.github/workflows/itf-frontend.yml'
  workflow_dispatch: 

jobs:
  build-and-test:
    
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: latest

      - name: Install dependencies
        run: npm install --prefix client/

      - name: Build
        run: npm run build --prefix client/
        
      - name: Test app
        run: npm run test --prefix client/
